FROM golang:1.26.1-alpine as builder

WORKDIR /sagio
COPY go.mod go.sum ./
RUN go mod download

RUN go install github.com/swaggo/swag/cmd/swag@latest

COPY . .

RUN swag init -g ./cmd/server/main.go
RUN CGO_ENABLED=0 GOOS=linux go build -o server ./cmd/server

FROM scratch

ENV DEBUG=true

WORKDIR /etc/sagio

COPY --from=builder /sagio/server .

ENTRYPOINT [ "/etc/sagio/server" ]